CFLAGS	= -O1 -g -DPLATFORM_YAROZE
LINKER	= -Xlinker -Ttext -Xlinker 80100000
RM	= del

PROG	= main
OBJS	= \
    main.c \
    CDROM.c \
    CDROM.s \
    CDPrompt.c \
    Interpt.c \
    File.c \
    Gamepad.c \
    Object.c \
    Maths.c \
    Stars.c \
    TIM.c \
    TMD.c \
    VRAM.c

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) $(LINKER) $(OBJS) -o $(PROG)

main.o: main.c

clean:
	$(RM) $(PROG) 
	$(RM) *.o

